### ISSUE TITLE
block_hotplug: test code threw exception because it called hotplug_hmp() on QDrive object

### ISSUE THREAD

**Issue by rayx** [autotest/tp-qemu#1572]
I tried this block_hotplug test, and it failed.

io-github-autotest-qemu.block_hotplug.default.block_virtio.fmt_qcow2.with_plug.default.one_pci

The error messages in log were: 

<pre><code>
2018-11-23 14:47:44,735 error_context    L0079 INFO | Context: Hotplug block device (iteration 0)
2018-11-23 14:47:44,736 virt_vm          L1146 DEBUG| Attempting to log into 'avocado-vt-vm1' (timeout 360s)
2018-11-23 14:48:18,329 ip_sniffing      L0053 DEBUG| Updated HWADDR (9a:fe:ff:00:01:02)<->(192.168.122.50) IP pair into address cache
2018-11-23 14:48:18,819 virt_vm          L0862 DEBUG| Found/Verified IP 192.168.122.50 for VM avocado-vt-vm1 NIC 0
2018-11-23 14:48:20,386 client           L1162 DEBUG| Sending command (safe): ls /dev/[hsv]d[a-z]* | sort
2018-11-23 14:48:20,699 stacktrace       L0041 ERROR|
2018-11-23 14:48:20,699 stacktrace       L0044 ERROR| Reproduced traceback from: /root/avocado-test/avocado-vt/avocado_vt/test.py:434
2018-11-23 14:48:20,702 stacktrace       L0047 ERROR| Traceback (most recent call last):
2018-11-23 14:48:20,702 stacktrace       L0047 ERROR|   File "/root/avocado-test/avocado-vt/virttest/error_context.py", line 135, in new_fn
2018-11-23 14:48:20,702 stacktrace       L0047 ERROR|     return fn(*args, **kwargs)
2018-11-23 14:48:20,703 stacktrace       L0047 ERROR|   File "/var/lib/avocado/data/avocado-vt/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/block_hotplug.py", line 98, in run
2018-11-23 14:48:20,703 stacktrace       L0047 ERROR|     ret = vm.devices.simple_hotplug(dev, vm.monitor)
2018-11-23 14:48:20,703 stacktrace       L0047 ERROR|   File "/root/avocado-test/avocado-vt/virttest/qemu_devices/qcontainer.py", line 625, in simple_hotplug
2018-11-23 14:48:20,704 stacktrace       L0047 ERROR|     out = device.hotplug(monitor)
2018-11-23 14:48:20,704 stacktrace       L0047 ERROR|   File "/root/avocado-test/avocado-vt/virttest/qemu_devices/qdevices.py", line 258, in hotplug
2018-11-23 14:48:20,704 stacktrace       L0047 ERROR|     return monitor.human_monitor_cmd(self.hotplug_hmp())
2018-11-23 14:48:20,704 stacktrace       L0047 ERROR|   File "/root/avocado-test/avocado-vt/virttest/qemu_devices/qdevices.py", line 267, in hotplug_hmp
2018-11-23 14:48:20,705 stacktrace       L0047 ERROR|     raise DeviceError("Hotplug is not supported by this device %s", self)
2018-11-23 14:48:20,705 stacktrace       L0047 ERROR| DeviceError: ('Hotplug is not supported by this device %s', <virttest.qemu_devices.qdevices.QDrive object at 0xffff87cdd910>)
2018-11-23 14:48:20,705 stacktrace       L0048 ERROR|
</code></pre>

I take at quick look at the code. QDrive class doesn't have that method indeed, but its child classes (e.g., QHPDrive) have. So this seems a test code to me (I use default test parameters). Is this a known issue?

**Comment by vivianQizhu** [comment]
@YongxueHong @lolyu Anyone help check this? Thanks.

**Comment by lolyu** [comment]
```python
        if self.has_hmp_cmd('__com.redhat_drive_add') and use_device:
            devices.append(qdevices.QRHDrive(name))
        elif self.has_hmp_cmd('drive_add') and use_device:
            devices.append(qdevices.QHPDrive(name))
        elif self.has_option("device"):
            devices.append(qdevices.QDrive(name, use_device))
        else:       # very old qemu without 'addr' support
            devices.append(qdevices.QOldDrive(name, use_device))
```
What QEMU version you are using? Since `QDrive` is selected in your case, I believe this is the main reason.

**Comment by rayx** [comment]
@lolyu My QEMU's version is 3.0.50, which is new enough. The code you posted seems to indicate this is a monitor type issue again (see https://github.com/autotest/tp-qemu/pull/1561/commits/f98a85e1b78b352e23e269bafdb8cee808ffbc37). However, setting monitor_type to "human" doesn't work in this case. I'll debug the test code and update the issue if I find something.

**Comment by rayx** [comment]
Thanks for the hint. I figure out why. It was because the command in DevContainer class that is used to get QEMU HMP and QMP commands don't work on aarch64. The recently merged commit https://github.com/autotest/tp-qemu/pull/1561/commits/f98a85e1b78b352e23e269bafdb8cee808ffbc37 fix this. I'll need to get that to run the test on aarch64. 

May I ask how you guys update avocado-vt code? Is it OK to just do a "git pull" in avocado-vt dir, or do I have to run the following commands after updating avocado-vt code?

<pre><code>
# cd ../avocado
# make link
# ./scripts/avocado vt-bootstrap
</pre></code>

**Comment by luckyh** [comment]
@rayx a `git pull` would work if the previous install is in `develop` mode (`make link`/`python setup.py develop`), otherwise a reinstall is needed.

**Comment by rayx** [comment]
@vivianQizhu I ran a few block_hotplug tests for sanity check. I observed this test failed:

  type_specific.io-github-autotest-qemu.block_hotplug.default.block_virtio.fmt_qcow2.with_plug.default.one_pci

and this test passed:

  type_specific.io-github-autotest-qemu.block_hotplug.default.block_scsi.fmt_qcow2.with_plug.default.one_pci

The first test failed due to the same reason as in https://github.com/autotest/tp-qemu/issues/1569 (it tried to plug a virito-blk-pci device to pcie root bus). The second test didn't have that issue because the device was plugged into a SCSI bus created by virtio-scsi-pci device, instead of pcie root bus. I think q35 should have the same result? 

BTW, does anyone know if there's a syntax in avocado cfg file to filter out 'block_virtio' section if machine is arm64-pci or arm64-mmio? (That should be useful for q35 machine too).

<pre><code>
    variants:
        -   block_virtio:
            drive_format_stg0 = virtio
            drive_format_stg1 = virtio
            get_disk_pattern = "^/dev/vd[a-z]*$"
        - block_scsi:
            drive_format_stg0 = scsi-hd
            drive_format_stg1 = scsi-hd
            get_disk_pattern = "^/dev/sd[a-z]*$"
</code></pre>

**Comment by vivianQizhu** [comment]
@rayx Would you help provide test log for it? Not sure the root cause without the detailed log, cuase I can recall I got it passed here https://github.com/avocado-framework/avocado-vt/pull/1653#issuecomment-402404577
Although simple_hotplug() got changed a bit but should not affect this one.

**Comment by rayx** [comment]
> Would you help provide test log for it? 

@vivianQizhu Please see the attached file: [job.log](https://github.com/autotest/tp-qemu/files/2614740/job.log)

It was generated by this command on an aarch64 system:

<pre><code>
# scripts/avocado run type_specific.io-github-autotest-qemu.block_hotplug.default.block_virtio.fmt_qcow2.with_plug.default.one_pci
</code></pre>

> Not sure the root cause without the detailed log, cuase I can recall I got it passed here [avocado-framework/avocado-vt#1653 (comment)](https://github.com/avocado-framework/avocado-vt/pull/1653#issuecomment-402404577)

That's strange. block_virtio tests did pass in your result.

**Comment by vivianQizhu** [comment]
@rayx Just run it again and passed, but the command is sent via qmp:
04:39:00 DEBUG| Send command: {'execute': '__com.redhat_drive_add', 'arguments': OrderedDict([('id', 'drive_stg0'), ('snapshot', 'off'), ('aio', 'threads'), ('cache', 'none'), ('format', 'qcow2'), ('file', '/home/kvm_autotest_root/images/storage0.qcow2')]), 'id': '9UrZGU2c'}
04:39:00 DEBUG| (monitor avocado-vt-vm1.qmpmonitor1) Sending command 'device_add'
04:39:00 DEBUG| Send command: {'execute': 'device_add', 'arguments': OrderedDict([('driver', 'virtio-blk-pci'), ('id', 'stg0'), ('drive', 'drive_stg0'), ('bus', 'pcie_root_port_0')]), 'id': 'AhQw3TeD'}

So guess there is something wrong with the hmp support. But qemu does not encourage test with hmp anyway. You should be able to use qmp. My configuration is:
```
04:38:18 DEBUG|     monitor_type = qmp
04:38:18 DEBUG|     monitors = qmpmonitor1
```
I suppose that the issue about QDrive and QHPDrive should not blame the monitor type.

**Comment by rayx** [comment]
Thanks for the information. Setting pcie_extra_root_port seems the simplest approach. I don't have access to my system today. Will give it a try tomorrow and send out a patch if it works fine.

**Comment by rayx** [comment]
Unfortunately there seems to be a bug with avocado-vt, which causes pcie_extra_root_port parameter not working. See https://github.com/avocado-framework/avocado-vt/issues/1847

I'll close this issue since the root cause is known.
