### ISSUE TITLE
RHEL.6.devel... unattended_install

### ISSUE THREAD

**Issue by Andrei-Stepanov** [autotest/tp-qemu#457]
Hello, it is not a bug. I believe.

But how do I install RHEL.6.devel using:

io-github-autotest-qemu.unattended_install.url.extra_cdrom_ks.default_install.aio_threads

?

It fails to find images/pxeboot/vmlinuz

All stable 6.X has this file. Even RHEL.7.devel has it..... but 6.devel does not

```
16:27:07 stacktrace       L0042 ERROR|   File "/mnt/tests/spice/qe-tests/avocado/virttest/tests/unattended_install.py", line 879, in setup_url
16:27:07 stacktrace       L0042 ERROR|     process.run(kernel_cmd, verbose=DEBUG)
16:27:07 stacktrace       L0042 ERROR|   File "/mnt/tests/spice/qe-tests/avocado/avocado/utils/process.py", line 949, in run
16:27:07 stacktrace       L0042 ERROR|     raise CmdError(cmd, sp.result)
16:27:07 stacktrace       L0042 ERROR| CmdError: Command 'wget -q http://download.englab.brq.redhat.com/pub/rhel/rel-eng/latest-RHEL-6*/compose/Workstation/i386/os/images/pxeboot/vmlinuz' failed (rc=8)
```

http://download.devel.redhat.com/rel-eng/latest-RHEL-6/compose/Workstation/x86_64/os/images/

**Comment by ypu** [comment]
Hi @Andrei-Stepanov seems the cfg file you using have some problem with the parameter 'url'. Based what you described you may have it filled with that value in RHEL.cfg or some cfg file is not only for one guest. You may need grep your cfg files with the key word 'url'. And remove it from that file and put them into each guests cfg file.

By the way from your log, seems your virt-test is not the newest. maybe you need update too.

**Comment by Andrei-Stepanov** [comment]
I have tried on upstream branch. Got the same result.
I specified **url** only at:

vim ./avocado-vt/shared/cfg/guest-os/Linux/RHEL/6.devel/x86_64.cfg
re-run: **avocado vt-bootstrap** to pick-up my changes...

```

avocado run --vt-guest-os Linux.RHEL.6.devel.x86_64 unattended_install.url.extra_cdrom_ks.default_install.aio_threads

11:03:52 job              L0299 INFO | Command line: /mnt/tests/spice/qe-tests/avocado/scripts/avocado run --vt-guest-os Linux.RHEL.6.devel.x86_64 unattended_install.url.extra_cdrom_ks.default_install.aio_threads
11:03:52 job              L0300 INFO | 
11:03:52 job              L0305 INFO | Avocado version: 0.27.0
11:03:52 job              L0314 INFO | Avocado git repo info
11:03:52 job              L0315 INFO | Top commit: c14cbfecfb7b422c36b3c358b21668ab1d829e8b
11:03:52 job              L0316 INFO | Branch: master
11:03:52 job              L0317 INFO | 
11:03:52 job              L0370 INFO | Plugins enabled:
11:03:53 job              L0372 INFO | config       Implements the avocado 'config' subcommand
11:03:53 job              L0372 INFO | distro       Implements the avocado 'distro' subcommand
11:03:53 job              L0372 INFO | exec_path    Implements the avocado 'exec-path' subcommand
11:03:53 job              L0372 INFO | gdb          Run tests with GDB goodies enabled
11:03:53 job              L0372 INFO | htmlresult   HTML job report
11:03:53 job              L0372 INFO | inner_runner Allows the use of an intermediary inner test runner
11:03:53 job              L0372 INFO | json         JSON output
11:03:53 job              L0372 INFO | journal      Test journal
11:03:53 job              L0372 INFO | multiplexer  Implements the avocado 'multiplex' subcommand
11:03:53 job              L0372 INFO | plugins_list Implements the avocado 'plugins' subcommand
11:03:53 job              L0372 INFO | run_remote   Run tests on a remote machine
11:03:53 job              L0372 INFO | sysinfo      Collect system information
11:03:53 job              L0372 INFO | test_lister  Implements the avocado 'list' subcommand
11:03:53 job              L0372 INFO | test_runner  Implements the avocado 'run' subcommand
11:03:53 job              L0372 INFO | vt_bootstrap Avocado VT - implements the 'vt-bootstrap' subcommand
11:03:53 job              L0372 INFO | vt           Avocado VT - legacy virt-test support
11:03:53 job              L0372 INFO | vt_lister    Avocado VT - implements legacy virt-test listing
11:03:53 job              L0372 INFO | wrapper      Implements the '--wrapper' flag for the 'run' subcommand
11:03:53 job              L0372 INFO | xunit        xUnit output
11:03:53 job              L0378 INFO | Plugins enabled:
11:03:53 job              L0380 INFO | run_vm Run tests on a Virtual Machine
11:03:53 job              L0392 INFO | 
11:03:53 job              L0322 INFO | Config files read (in order):
11:03:53 job              L0324 INFO | /mnt/tests/spice/qe-tests/avocado/etc/avocado/avocado.conf
11:03:53 job              L0324 INFO | /mnt/tests/spice/qe-tests/avocado/etc/avocado/conf.d/gdb.conf
11:03:53 job              L0324 INFO | /mnt/tests/spice/qe-tests/avocado/etc/avocado/conf.d/vt.conf
11:03:53 job              L0329 INFO | 
11:03:53 job              L0331 INFO | Avocado config:
11:03:53 job              L0340 INFO | Section.Key                             Value
11:03:53 job              L0340 INFO | datadir.paths.base_dir                  /mnt/tests/spice/qe-tests/avocado-base
11:03:53 job              L0340 INFO | datadir.paths.data_dir                  /mnt/tests/spice/qe-tests/avocado-data
11:03:53 job              L0340 INFO | datadir.paths.logs_dir                  /mnt/tests/spice/qe-tests/avocado-logs
11:03:53 job              L0340 INFO | datadir.paths.test_dir                  /usr/share/avocado/tests
11:03:53 job              L0340 INFO | sysinfo.collect.enabled                 True
11:03:53 job              L0340 INFO | sysinfo.collect.installed_packages      False
11:03:53 job              L0340 INFO | sysinfo.collect.profiler                False
11:03:53 job              L0340 INFO | sysinfo.collectibles.commands           /etc/avocado/sysinfo/commands
11:03:53 job              L0340 INFO | sysinfo.collectibles.files              /etc/avocado/sysinfo/files
11:03:53 job              L0340 INFO | sysinfo.collectibles.profilers          /etc/avocado/sysinfo/profilers
11:03:53 job              L0340 INFO | runner.output.colored                   True
11:03:53 job              L0340 INFO | runner.output.utf8                      
11:03:53 job              L0340 INFO | runner.behavior.keep_tmp_files          False
11:03:53 job              L0340 INFO | job.output.loglevel                     debug
11:03:53 job              L0340 INFO | restclient.connection.hostname          localhost
11:03:53 job              L0340 INFO | restclient.connection.port              9405
11:03:53 job              L0340 INFO | restclient.connection.username          
11:03:53 job              L0340 INFO | restclient.connection.password          
11:03:53 job              L0340 INFO | plugins.skip_broken_plugin_notification []
11:03:53 job              L0340 INFO | plugins.loader_plugins_priority         ['file']
11:03:53 job              L0340 INFO | gdb.paths.gdb                           /usr/bin/gdb
11:03:53 job              L0340 INFO | gdb.paths.gdbserver                     /usr/bin/gdbserver
11:03:53 job              L0340 INFO | vt.setup.backup_image_before_test       True
11:03:53 job              L0340 INFO | vt.setup.restore_image_after_test       True
11:03:53 job              L0340 INFO | vt.setup.keep_guest_running             False
11:03:53 job              L0340 INFO | vt.common.data_dir                      
11:03:53 job              L0340 INFO | vt.common.type_specific_only            False
11:03:53 job              L0340 INFO | vt.common.mem                           1024
11:03:53 job              L0340 INFO | vt.common.arch                          
11:03:53 job              L0340 INFO | vt.common.machine_type                  
11:03:53 job              L0340 INFO | vt.common.nettype                       
11:03:53 job              L0340 INFO | vt.common.netdst                        virbr0
11:03:53 job              L0340 INFO | vt.qemu.qemu_bin                        
11:03:53 job              L0340 INFO | vt.qemu.qemu_dst_bin                    
11:03:53 job              L0340 INFO | vt.qemu.accel                           kvm
11:03:53 job              L0340 INFO | vt.qemu.vhost                           off
11:03:53 job              L0340 INFO | vt.qemu.monitor                         human
11:03:53 job              L0340 INFO | vt.qemu.smp                             2
11:03:53 job              L0340 INFO | vt.qemu.image_type                      qcow2
11:03:53 job              L0340 INFO | vt.qemu.nic_model                       virtio_net
11:03:53 job              L0340 INFO | vt.qemu.disk_bus                        virtio_blk
11:03:53 job              L0340 INFO | vt.qemu.sandbox                         on
11:03:53 job              L0340 INFO | vt.qemu.defconfig                       yes
11:03:53 job              L0340 INFO | vt.qemu.malloc_perturb                  yes
11:03:53 job              L0340 INFO | vt.libvirt.connect_uri                  qemu:///session
11:03:53 job              L0340 INFO | vt.debug.no_cleanup                     False
11:03:53 job              L0341 INFO | 
11:03:53 job              L0346 INFO | Avocado Data Directories:
11:03:53 job              L0347 INFO | 
11:03:53 job              L0348 INFO | Avocado replaces config dirs that can't be accessed
11:03:53 job              L0349 INFO | with sensible defaults. Please edit your local config
11:03:53 job              L0350 INFO | file to customize values
11:03:53 job              L0351 INFO | 
11:03:53 job              L0352 INFO | base     /mnt/tests/spice/qe-tests/avocado-base
11:03:53 job              L0353 INFO | tests    /mnt/tests/spice/qe-tests/avocado/examples/tests
11:03:53 job              L0354 INFO | data     /mnt/tests/spice/qe-tests/avocado-data
11:03:53 job              L0355 INFO | logs     /mnt/tests/spice/qe-tests/avocado-logs
11:03:53 job              L0356 INFO | 
11:03:53 job              L0406 INFO | Temporary dir: /var/tmp/avocado_4maMDf
11:03:53 job              L0407 INFO | 
11:03:53 job              L0414 INFO | Variant 1:    /
11:03:53 job              L0417 INFO | 
11:03:53 job              L0292 INFO | Job ID: a747a6d15e733c8408c5ca3f5bb1cf23627d24d7
11:03:53 job              L0293 INFO | 
11:03:53 test             L0153 INFO | START io-github-autotest-qemu.unattended_install.url.extra_cdrom_ks.default_install.aio_threads
11:03:53 vt               L0369 INFO | Avocado-VT '0.27.0-152-g5cb5', Branch 'master', SHA1 '5cb56934ffffe866aab27b87989570343c9dd77d'
11:03:53 vt               L0371 INFO | Starting test 0
11:03:53 vt               L0372 DEBUG| Test parameters:
11:03:53 vt               L0376 DEBUG|     _name_map_file = {'tests.cfg': 'qemu_kvm_jeos_quick', 'machines.cfg': 'i440fx', 'subtests.cfg': '(subtest=io-github-autotest-qemu).(subtest=unattended_install).url.extra_cdrom_ks.default_install.aio_threads', 'guest-hw.cfg': 'bridge.default_bios.no_virtio_rng.(image_backend=filesystem).no_9p_export.smallpages.no_pci_assignable.qcow2.virtio_blk.smp2.virtio_net', 'guest-os.cfg': 'Linux.RHEL.6.devel.x86_64'}
11:03:53 vt               L0376 DEBUG|     _short_name_map_file = {'tests.cfg': 'qemu_kvm_jeos_quick', 'machines.cfg': 'i440fx', 'subtests.cfg': 'io-github-autotest-qemu.unattended_install.url.extra_cdrom_ks.default_install.aio_threads', 'guest-hw.cfg': 'bridge.default_bios.no_virtio_rng.filesystem.no_9p_export.smallpages.no_pci_assignable.qcow2.virtio_blk.smp2.virtio_net', 'guest-os.cfg': 'Linux.RHEL.6.devel.x86_64'}
11:03:53 vt               L0376 DEBUG|     auto_cpu_model = yes
11:03:53 vt               L0376 DEBUG|     avocado_inject_params = True
11:03:53 vt               L0376 DEBUG|     avocado_params = ([TreeNode(name='')], ['/run/*'])
11:03:53 vt               L0376 DEBUG|     backup_dir = images/
11:03:53 vt               L0376 DEBUG|     backup_image = yes
11:03:53 vt               L0376 DEBUG|     backup_image_before_testing = yes
11:03:53 vt               L0376 DEBUG|     backup_image_on_check_error = no
11:03:53 vt               L0376 DEBUG|     boot_menu = off
11:03:53 vt               L0376 DEBUG|     boot_once = c
11:03:53 vt               L0376 DEBUG|     boot_order = cdn
11:03:53 vt               L0376 DEBUG|     boot_path = images/pxeboot
11:03:53 vt               L0376 DEBUG|     catch_monitor = catch_monitor
11:03:53 vt               L0376 DEBUG|     cd_format = ide
11:03:53 vt               L0376 DEBUG|     cdrom_check_cdrom_pattern = /dev/cdrom-\w+|/dev/cdrom\d*
11:03:53 vt               L0376 DEBUG|     cdrom_get_cdrom_cmd = ls /dev/cdrom*
11:03:53 vt               L0376 DEBUG|     cdrom_info_cmd = cat /proc/sys/dev/cdrom/info
11:03:53 vt               L0376 DEBUG|     cdrom_test_cmd = dd if=%s of=/dev/null bs=1 count=1
11:03:53 vt               L0376 DEBUG|     cdrom_unattended = images/rhel6devel-64/ks.iso
11:03:53 vt               L0376 DEBUG|     cdroms = cd1 unattended
11:03:53 vt               L0376 DEBUG|     check_image = yes
11:03:53 vt               L0376 DEBUG|     cmds_installed_host = 
11:03:53 vt               L0376 DEBUG|     connect_uri = default
11:03:53 vt               L0376 DEBUG|     convert_ppm_files_to_png = no
11:03:53 vt               L0376 DEBUG|     cpu_chk_cmd = grep -c processor /proc/cpuinfo
11:03:53 vt               L0376 DEBUG|     cpu_model_flags = 
11:03:53 vt               L0376 DEBUG|     dep = []
11:03:53 vt               L0376 DEBUG|     display = vnc
11:03:53 vt               L0376 DEBUG|     drive_format = virtio
11:03:53 vt               L0376 DEBUG|     drive_index_cd1 = 2
11:03:53 vt               L0376 DEBUG|     drive_index_image1 = 0
11:03:53 vt               L0376 DEBUG|     drive_index_unattended = 1
11:03:53 vt               L0376 DEBUG|     drive_rerror_image1 = 
11:03:53 vt               L0376 DEBUG|     drive_werror_image1 = 
11:03:53 vt               L0376 DEBUG|     enable_msix_vectors = yes
11:03:53 vt               L0376 DEBUG|     enable_pvpanic = yes
11:03:53 vt               L0376 DEBUG|     encode_video_files = yes
11:03:53 vt               L0376 DEBUG|     file_transfer_client = scp
11:03:53 vt               L0376 DEBUG|     file_transfer_port = 22
11:03:53 vt               L0376 DEBUG|     force_create_image = yes
11:03:53 vt               L0376 DEBUG|     grub_file = /boot/grub/grub.conf
11:03:53 vt               L0376 DEBUG|     guest_port_remote_shell = 22
11:03:53 vt               L0376 DEBUG|     guest_port_unattended_install = 12323
11:03:53 vt               L0376 DEBUG|     id = io-github-autotest-qemu.unattended_install.url.extra_cdrom_ks.default_install.aio_threads
11:03:53 vt               L0376 DEBUG|     image_aio = threads
11:03:53 vt               L0376 DEBUG|     image_backend = filesystem
11:03:53 vt               L0376 DEBUG|     image_boot = yes
11:03:53 vt               L0376 DEBUG|     image_chain = 
11:03:53 vt               L0376 DEBUG|     image_clone_command = cp --reflink=auto %s %s
11:03:53 vt               L0376 DEBUG|     image_copy_on_error = no
11:03:53 vt               L0376 DEBUG|     image_format = qcow2
11:03:53 vt               L0376 DEBUG|     image_name = images/rhel6devel-64
11:03:53 vt               L0376 DEBUG|     image_raw_device = no
11:03:53 vt               L0376 DEBUG|     image_remove_command = rm -rf %s
11:03:53 vt               L0376 DEBUG|     image_size = 10G
11:03:53 vt               L0376 DEBUG|     image_unbootable_pattern = Hard Disk.*not a bootable disk
11:03:53 vt               L0376 DEBUG|     image_verify_bootable = no
11:03:53 vt               L0376 DEBUG|     images = image1
11:03:53 vt               L0376 DEBUG|     inactivity_treshold = 1800
11:03:53 vt               L0376 DEBUG|     inactivity_watcher = error
11:03:53 vt               L0376 DEBUG|     indirect_image_blacklist = /dev/hda[\d]* /dev/sda[\d]* /dev/sg0 /dev/md0
11:03:53 vt               L0376 DEBUG|     initrd = images/rhel6devel-64/initrd.img
11:03:53 vt               L0376 DEBUG|     install_virtio = no
11:03:53 vt               L0376 DEBUG|     ioport_pvpanic = 0x505
11:03:53 vt               L0376 DEBUG|     keep_ppm_files = no
11:03:53 vt               L0376 DEBUG|     keep_ppm_files_on_error = no
11:03:53 vt               L0376 DEBUG|     keep_screendumps = yes
11:03:53 vt               L0376 DEBUG|     keep_screendumps_on_error = yes
11:03:53 vt               L0376 DEBUG|     keep_video_files = yes
11:03:53 vt               L0376 DEBUG|     keep_video_files_on_error = yes
11:03:53 vt               L0376 DEBUG|     kernel = images/rhel6devel-64/vmlinuz
11:03:53 vt               L0376 DEBUG|     kernel_params = ks=cdrom nicdelay=60  console=ttyS0,115200 console=tty0
11:03:53 vt               L0376 DEBUG|     kill_timeout = 60
11:03:53 vt               L0376 DEBUG|     kill_unresponsive_vms = yes
11:03:53 vt               L0376 DEBUG|     kill_vm = yes
11:03:53 vt               L0376 DEBUG|     kill_vm_before_test = no
11:03:53 vt               L0376 DEBUG|     kill_vm_gracefully = yes
11:03:53 vt               L0376 DEBUG|     kill_vm_on_error = yes
11:03:53 vt               L0376 DEBUG|     local_ip = ENTER.YOUR.LOCAL.EXAMPLE.COM
11:03:53 vt               L0376 DEBUG|     local_pwd = 
11:03:53 vt               L0376 DEBUG|     login_timeout = 360
11:03:53 vt               L0376 DEBUG|     lowest_mem = 512
11:03:53 vt               L0376 DEBUG|     machine_type = pc
11:03:53 vt               L0376 DEBUG|     main_vm = avocado-vt-vm1
11:03:53 vt               L0376 DEBUG|     malloc_perturb = yes
11:03:53 vt               L0376 DEBUG|     medium = url
11:03:53 vt               L0376 DEBUG|     mem = 1024
11:03:53 vt               L0376 DEBUG|     mem_chk_cmd = dmidecode -t 17 | awk -F: '/Size/ {print $2}'
11:03:53 vt               L0376 DEBUG|     mem_chk_cur_cmd = grep MemTotal /proc/meminfo
11:03:53 vt               L0376 DEBUG|     mem_chk_re_str = [^\$]([0-9]+)
11:03:53 vt               L0376 DEBUG|     memballoon_model = virtio
11:03:53 vt               L0376 DEBUG|     migrate_dest_host = ENTER.YOUR.DEST.EXAMPLE.COM
11:03:53 vt               L0376 DEBUG|     migrate_dest_pwd = PASSWORD.DEST.EXAMPLE
11:03:53 vt               L0376 DEBUG|     migrate_load_vms = 
11:03:53 vt               L0376 DEBUG|     migrate_main_vm = avocado-vt-vm1
11:03:53 vt               L0376 DEBUG|     migrate_port = 49152
11:03:53 vt               L0376 DEBUG|     migrate_proto = tcp
11:03:53 vt               L0376 DEBUG|     migrate_shared_storage = SHARED_IMAGE.EXAMPLE
11:03:53 vt               L0376 DEBUG|     migrate_source_host = ENTER.YOUR.SOURCE.EXAMPLE.COM
11:03:53 vt               L0376 DEBUG|     migrate_source_pwd = PASSWORD.SOURCE.EXAMPLE
11:03:53 vt               L0376 DEBUG|     migrate_vms = 
11:03:53 vt               L0376 DEBUG|     monitor_type = human
11:03:53 vt               L0376 DEBUG|     monitors = hmp1
11:03:53 vt               L0376 DEBUG|     name = qemu_kvm_jeos_quick.bridge.default_bios.no_virtio_rng.(image_backend=filesystem).no_9p_export.smallpages.no_pci_assignable.qcow2.virtio_blk.smp2.virtio_net.Linux.RHEL.6.devel.x86_64.i440fx.(subtest=io-github-autotest-qemu).(subtest=unattended_install).url.extra_cdrom_ks.default_install.aio_threads
11:03:53 vt               L0376 DEBUG|     netdev_peer_re = \s{2,}(.*?): .*?\\\s(.*?):
11:03:53 vt               L0376 DEBUG|     netdst = virbr0
11:03:53 vt               L0376 DEBUG|     nettype = user
11:03:53 vt               L0376 DEBUG|     nic_model = virtio
11:03:53 vt               L0376 DEBUG|     nics = nic1
11:03:53 vt               L0376 DEBUG|     os_type = linux
11:03:53 vt               L0376 DEBUG|     os_variant = rhel6
11:03:53 vt               L0376 DEBUG|     other_tests_dirs = 
11:03:53 vt               L0376 DEBUG|     password = 123456
11:03:53 vt               L0376 DEBUG|     paused_after_start_vm = no
11:03:53 vt               L0376 DEBUG|     pci_assignable = no
11:03:53 vt               L0376 DEBUG|     profilers = kvm_stat
11:03:53 vt               L0376 DEBUG|     provider = io-github-autotest-qemu
11:03:53 vt               L0376 DEBUG|     qemu_binary = /usr/libexec/qemu-kvm
11:03:53 vt               L0376 DEBUG|     qemu_dst_binary = /usr/libexec/qemu-kvm
11:03:53 vt               L0376 DEBUG|     qemu_img_binary = /bin/qemu-img
11:03:53 vt               L0376 DEBUG|     qemu_io_binary = /bin/qemu-io
11:03:53 vt               L0376 DEBUG|     reboot_command = shutdown -r now
11:03:53 vt               L0376 DEBUG|     redirs = remote_shell
11:03:53 vt               L0376 DEBUG|     remote_ip = ENTER.YOUR.REMOTE.EXAMPLE.COM
11:03:53 vt               L0376 DEBUG|     remote_pwd = 
11:03:53 vt               L0376 DEBUG|     remote_user = root
11:03:53 vt               L0376 DEBUG|     restore_image = no
11:03:53 vt               L0376 DEBUG|     restore_image_after_testing = yes
11:03:53 vt               L0376 DEBUG|     restore_image_on_check_error = no
11:03:53 vt               L0376 DEBUG|     run_tcpdump = yes
11:03:53 vt               L0376 DEBUG|     screendump_delay = 5
11:03:53 vt               L0376 DEBUG|     screendump_quality = 30
11:03:53 vt               L0376 DEBUG|     screendump_temp_dir = /dev/shm
11:03:53 vt               L0376 DEBUG|     screendump_verbose = no
11:03:53 vt               L0376 DEBUG|     serials = serial0
11:03:53 vt               L0376 DEBUG|     shell_client = ssh
11:03:53 vt               L0376 DEBUG|     shell_port = 22
11:03:53 vt               L0376 DEBUG|     shell_prompt = ^\[.*\][\#\$]\s*$
11:03:53 vt               L0376 DEBUG|     shortname = qcow2.virtio_blk.smp2.virtio_net.RHEL.6.devel.x86_64.io-github-autotest-qemu.unattended_install.url.extra_cdrom_ks.default_install.aio_threads
11:03:53 vt               L0376 DEBUG|     shutdown_cleanly = yes
11:03:53 vt               L0376 DEBUG|     shutdown_cleanly_timeout = 120
11:03:53 vt               L0376 DEBUG|     shutdown_command = shutdown -h now
11:03:53 vt               L0376 DEBUG|     skip_cluster_leak_warn = no
11:03:53 vt               L0376 DEBUG|     skip_image_check_during_running = no
11:03:53 vt               L0376 DEBUG|     skip_image_processing = no
11:03:53 vt               L0376 DEBUG|     smp = 2
11:03:53 vt               L0376 DEBUG|     start_vm = no
11:03:53 vt               L0376 DEBUG|     status_test_command = echo $?
11:03:53 vt               L0376 DEBUG|     store_vm_register = yes
11:03:53 vt               L0376 DEBUG|     strict_mode = no
11:03:53 vt               L0376 DEBUG|     subtest = io-github-autotest-qemu.unattended_install
11:03:53 vt               L0376 DEBUG|     syslog_server_enabled = no
11:03:53 vt               L0376 DEBUG|     syslog_server_proto = udp
11:03:53 vt               L0376 DEBUG|     take_regular_screendumps = yes
11:03:53 vt               L0376 DEBUG|     test_timeout = 14400
11:03:53 vt               L0376 DEBUG|     type = unattended_install
11:03:53 vt               L0376 DEBUG|     unattended_delivery_method = cdrom
11:03:53 vt               L0376 DEBUG|     unattended_file = unattended/RHEL-6-spice.ks
11:03:53 vt               L0376 DEBUG|     url = http://download.englab.brq.redhat.com/pub/rhel/rel-eng/latest-RHEL-6*/compose/Workstation/x86_64/os
11:03:53 vt               L0376 DEBUG|     url_auto_ip = 192.168.122.1
11:03:53 vt               L0376 DEBUG|     usb_bus = usb1.0
11:03:53 vt               L0376 DEBUG|     usb_controller = ehci
11:03:53 vt               L0376 DEBUG|     usb_devices = tablet1
11:03:53 vt               L0376 DEBUG|     usb_max_port = 6
11:03:53 vt               L0376 DEBUG|     usb_type = ich9-usb-ehci1
11:03:53 vt               L0376 DEBUG|     usb_type_tablet1 = usb-tablet
11:03:53 vt               L0376 DEBUG|     usb_type_usb1 = ich9-usb-ehci1
11:03:53 vt               L0376 DEBUG|     usbs = usb1
11:03:53 vt               L0376 DEBUG|     use_autostart = no
11:03:53 vt               L0376 DEBUG|     use_check_cpu = yes
11:03:53 vt               L0376 DEBUG|     use_debug = yes
11:03:53 vt               L0376 DEBUG|     use_no_reboot = no
11:03:53 vt               L0376 DEBUG|     use_os_type = yes
11:03:53 vt               L0376 DEBUG|     use_os_variant = no
11:03:53 vt               L0376 DEBUG|     use_virt_install_wait = no
11:03:53 vt               L0376 DEBUG|     used_cpus = 2
11:03:53 vt               L0376 DEBUG|     used_mem = 512
11:03:53 vt               L0376 DEBUG|     username = root
11:03:53 vt               L0376 DEBUG|     vcpu_thread_pattern = thread_id.?[:|=]\s*(\d+)
11:03:53 vt               L0376 DEBUG|     verify_host_dmesg = yes
11:03:53 vt               L0376 DEBUG|     vfd_size = 1440k
11:03:53 vt               L0376 DEBUG|     vga = std
11:03:53 vt               L0376 DEBUG|     virt_install_wait_time = 300
11:03:53 vt               L0376 DEBUG|     virt_test_type = qemu libvirt
11:03:53 vt               L0376 DEBUG|     vm_arch_name = x86_64
11:03:53 vt               L0376 DEBUG|     vm_register_delay = 5
11:03:53 vt               L0376 DEBUG|     vm_type = qemu
11:03:53 vt               L0376 DEBUG|     vms = avocado-vt-vm1
11:03:53 vt               L0376 DEBUG|     vnc_autoport = yes
11:03:53 vt               L0380 WARNI| 
11:03:53 vt               L0381 WARNI| Testing with nettype='user' while running as root may produce unexpected results!!!
11:03:53 vt               L0383 WARNI| 
11:03:53 vt               L0440 DEBUG| Searching for test modules that match 'type = unattended_install' and 'provider = io-github-autotest-qemu' on this cartesian dict
11:03:53 vt               L0454 DEBUG| Found subtest module /mnt/tests/spice/qe-tests/avocado-data/avocado-vt/test-providers.d/downloads/io-github-autotest-qemu/generic/tests/unattended_install.py
11:03:53 env_process      L0662 DEBUG| KVM version: 3.10.0-229.el7.x86_64
11:03:53 env_process      L0683 DEBUG| KVM userspace version: 1.5.3 (qemu-kvm-1.5.3-86.el7)
11:03:53 process          L0272 INFO | Running 'true'
11:03:53 storage          L0415 DEBUG| Image backup /mnt/tests/spice/qe-tests/avocado-data/avocado-vt/images/rhel6devel-64.qcow2.backup already exists, skipping...
11:03:53 env_process      L0088 INFO | Create image on local fs.
11:03:53 error_context    L0079 INFO | Context: preprocessing --> Create image by command: /bin/qemu-img create -f qcow2 /mnt/tests/spice/qe-tests/avocado-data/avocado-vt/images/rhel6devel-64.qcow2 10G
11:03:53 env_process      L1316 WARNI| avocado-vt-vm1 is not alive. Can't query the register status
11:03:53 unattended_insta L0938 INFO | Starting unattended install setup
11:03:53 utils_net        L1099 DEBUG| Host does not support OpenVSwitch: Command 'ovs-vswitchd' could not be found in any of the PATH dirs: ['/usr/lib64/qt-3.3/bin', '/bin', '/sbin', '/mnt/tests/spice/qe-tests/avocado/virttest', '/usr/bin', '/usr/local/sbin', '/usr/libexec', '/mnt/tests/spice/qe-tests/avocado/scripts', '/root/bin', '/usr/sbin', '/usr/local/bin', '/mnt/tests/spice/qe-tests/avocado/libexec']
11:03:53 qemu_storage     L0475 DEBUG| Checking image file /mnt/tests/spice/qe-tests/avocado-data/avocado-vt/images/rhel6devel-64.qcow2
11:03:53 storage          L0415 DEBUG| Image backup /mnt/tests/spice/qe-tests/avocado-data/avocado-vt/images/rhel6devel-64.qcow2.backup already exists, skipping...
11:03:53 storage          L0328 DEBUG| Copying /mnt/tests/spice/qe-tests/avocado-data/avocado-vt/images/rhel6devel-64.qcow2 -> /mnt/tests/spice/qe-tests/avocado-data/avocado-vt/images/rhel6devel-64.qcow2.backup
11:03:53 env_process      L1302 DEBUG| Thread quit. Used to failed to get register info from guest 20150911-143055-61NM6Doc for 2 times.
11:03:53 process          L0272 INFO | Running 'true'
11:03:53 stacktrace       L0036 ERROR| 
11:03:53 stacktrace       L0039 ERROR| Reproduced traceback from: /mnt/tests/spice/qe-tests/avocado/avocado/core/plugins/vt.py:559
11:03:53 stacktrace       L0042 ERROR| Traceback (most recent call last):
11:03:53 stacktrace       L0042 ERROR|   File "/mnt/tests/spice/qe-tests/avocado/avocado/core/plugins/vt.py", line 350, in runTest
11:03:53 stacktrace       L0042 ERROR|     self._runTest()
11:03:53 stacktrace       L0042 ERROR|   File "/mnt/tests/spice/qe-tests/avocado/avocado/core/plugins/vt.py", line 478, in _runTest
11:03:53 stacktrace       L0042 ERROR|     run_func(self, params, env)
11:03:53 stacktrace       L0042 ERROR|   File "/mnt/tests/spice/qe-tests/avocado-data/avocado-vt/test-providers.d/downloads/io-github-autotest-qemu/generic/tests/unattended_install.py", line 14, in run
11:03:53 stacktrace       L0042 ERROR|     unattended_install.run(test, params, env)
11:03:53 stacktrace       L0042 ERROR|   File "/mnt/tests/spice/qe-tests/avocado/virttest/error_context.py", line 135, in new_fn
11:03:53 stacktrace       L0042 ERROR|     return fn(*args, **kwargs)
11:03:53 stacktrace       L0042 ERROR|   File "/mnt/tests/spice/qe-tests/avocado/virttest/tests/unattended_install.py", line 1080, in run
11:03:53 stacktrace       L0042 ERROR|     unattended_install_config.setup()
11:03:53 stacktrace       L0042 ERROR|   File "/mnt/tests/spice/qe-tests/avocado/virttest/tests/unattended_install.py", line 951, in setup
11:03:53 stacktrace       L0042 ERROR|     self.setup_url()
11:03:53 stacktrace       L0042 ERROR|   File "/mnt/tests/spice/qe-tests/avocado/virttest/error_context.py", line 135, in new_fn
11:03:53 stacktrace       L0042 ERROR|     return fn(*args, **kwargs)
11:03:53 stacktrace       L0042 ERROR|   File "/mnt/tests/spice/qe-tests/avocado/virttest/tests/unattended_install.py", line 879, in setup_url
11:03:53 stacktrace       L0042 ERROR|     process.run(kernel_cmd, verbose=DEBUG)
11:03:53 stacktrace       L0042 ERROR|   File "/mnt/tests/spice/qe-tests/avocado/avocado/utils/process.py", line 949, in run
11:03:53 stacktrace       L0042 ERROR|     raise CmdError(cmd, sp.result)
11:03:53 stacktrace       L0042 ERROR| CmdError: Command 'wget -q http://download.englab.brq.redhat.com/pub/rhel/rel-eng/latest-RHEL-6*/compose/Workstation/x86_64/os/images/pxeboot/vmlinuz' failed (rc=8)
11:03:53 stacktrace       L0043 ERROR| 
11:03:53 test             L0482 ERROR| Traceback (most recent call last):

11:03:53 test             L0482 ERROR|   File "/mnt/tests/spice/qe-tests/avocado/avocado/core/plugins/vt.py", line 601, in _run_avocado
    raise test_exception

11:03:53 test             L0482 ERROR| CmdError: Command 'wget -q http://download.englab.brq.redhat.com/pub/rhel/rel-eng/latest-RHEL-6*/compose/Workstation/x86_64/os/images/pxeboot/vmlinuz' failed (rc=8)

11:03:53 test             L0499 ERROR| ERROR io-github-autotest-qemu.unattended_install.url.extra_cdrom_ks.default_install.aio_threads -> CmdError: Command 'wget -q http://download.englab.brq.redhat.com/pub/rhel/rel-eng/latest-RHEL-6*/compose/Workstation/x86_64/os/images/pxeboot/vmlinuz' failed (rc=8)
11:03:53 test             L0486 INFO | 

```

**Comment by lmr** [comment]
I'm closing this as this is not an avocado-vt issue per se.

**Comment by Andrei-Stepanov** [comment]
I am quite sure that it is impossible to install RHEL.6.devel right now with unattended_install.url.
unattended_install  - is a part of avocado-vt + tp-qemu.
Why did you close it ?

**Comment by lmr** [comment]
1) See comment above
2) RHEL6 is not supposed to have correct URL in their config files, as it's a system that requires a subscription.

**Comment by Andrei-Stepanov** [comment]
RHEL.6.devel stated as possible guest system 

avocado list --vt-list-guest

How do you suppose install / deploy it ?

**Comment by lmr** [comment]
1) By setting the correct URL in the config files yourself. Your URL has an asterisk in it (not to mention it's terrible to paste internal URLs on an external issue tracker), that's likely to be the reason why you are getting the install error.

2) Because they are there waiting for users to fill them out with correct information that, once again, can't be posted on a public repository.

**Comment by lmr** [comment]
All public information that can help is there. What is not there is things that we can't possibly ship, such as internal locations for subscription only OS.
