### ISSUE TITLE
rv_input: empty keycodes file causes exception

### ISSUE THREAD

**Issue by etrunko** [autotest/tp-qemu#585]
As far as I understand, this test sends some keycodes to the guest with different keymaps and stores the typed keycodes in a file in /tmp directory of the guest. In the end it will fetch that file and compare the results.

For some reason, the result file is empty, causing an exception in the test.

```
2016-04-12 21:47:12,571 remote           L0464 DEBUG| Trying to SCP with command 'scp -v -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o PreferredAuthentications=password -r  -P 22 test@\[192.168.122.46\]:/tmp/autotest-rv_input /tmp/autotest-rv_input', timeout 60s
2016-04-12 21:47:13,238 remote           L0414 DEBUG| Got password prompt, sending '123456'
2016-04-12 21:47:13,610 remote           L0441 DEBUG| SCP process terminated with status 0
2016-04-12 21:47:13,611 rv_input         L0257 INFO | Caught keycodes:[]
...
2016-04-12 21:47:19,462 stacktrace       L0039 ERROR| Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado_vt/test.py:400
2016-04-12 21:47:19,463 stacktrace       L0042 ERROR| Traceback (most recent call last):
2016-04-12 21:47:19,463 stacktrace       L0042 ERROR|   File "/usr/lib/python2.7/site-packages/avocado_vt/test.py", line 176, in runTest
2016-04-12 21:47:19,463 stacktrace       L0042 ERROR|     self._runTest()
2016-04-12 21:47:19,463 stacktrace       L0042 ERROR|   File "/usr/lib/python2.7/site-packages/avocado_vt/test.py", line 318, in _runTest
2016-04-12 21:47:19,463 stacktrace       L0042 ERROR|     run_func(self, params, env)
2016-04-12 21:47:19,463 stacktrace       L0042 ERROR|   File "/usr/share/avocado/data/avocado-vt/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/rv_input.py", line 323, in run
2016-04-12 21:47:19,463 stacktrace       L0042 ERROR|     result = analyze_results(result_path, test_type)
2016-04-12 21:47:19,464 stacktrace       L0042 ERROR|   File "/usr/share/avocado/data/avocado-vt/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/rv_input.py", line 259, in analyze_results
2016-04-12 21:47:19,464 stacktrace       L0042 ERROR|     if not (test_keycodes[i] == correct_keycodes[i]):
2016-04-12 21:47:19,464 stacktrace       L0042 ERROR| IndexError: list index out of range
```

Full log attached.
[rv_input.txt](https://github.com/autotest/tp-qemu/files/217980/rv_input.txt)

**Comment by xutian** [comment]
do you still meet above issue, if yes can you change keycode file from /tmp/autotest-rv_input to  ~/autotest-rv_input then have try?

Thanks,
Xu
